### PR TITLE
Compiler plugins

### PR DESCRIPTION
**Pull request by RDIL**
This implements plugin support to the compiler so anybody who wants to can add, remove, or tweak existing features.

The concepts, names of classes, fields, and methods are admittedly partially stolen from https://github.com/SpongePowered/Mixin

### CODE REVIEW

**Comment by RDIL** [comment]
@N8python can I get a review on this work so far

**Comment by N8python** [comment]
I will review soon.

**Comment by N8python** [comment]
Once the build passes I will review

**Comment by N8python** [comment]
@RDIL, I really like what you've done here. The plugin system looks awesome. Because it is based off Java - I'm going to take what you've done, implement the the plugin system in a more JavaScripty way, than you can look at and review my work. Thank you so much for the amazing idea.

**Comment by N8python** [comment]
`goroutines` and `coroutines` are two different things. `Goroutines` are inspired by the language `go`, which supports functions that communicate asynchronously across channels. This is what Z uses.

**Comment by RDIL** [comment]
When is this going to be finished

**Comment by N8python** [comment]
I don't feel like this goes with the style of Z, so I'm not going to merge it. I'll publish a reworked compiler plugin system at some point - thank you for the inspiration.

**Pull request closed without merging**
