### PR TITLE
New Plugin System

### PR DESCRIPTION
**Pull request by N8python**
This outlines a plugin system based of @RDIL's implementation - but with different functions and naming schemes.

### CODE REVIEW

**Comment by RDIL** [comment]
Oh I see what your doing
Trying to steal my system

**Comment by N8python** [comment]
I'm not trying to steal anything. I'm working on a different plugin system/idea, and if you don't like it, we don't have to go through with it. I'm just trying to show you what I'm thinking - since you proposed the idea, we can go through with your pull request (with modifications) if you want.

**Comment by RDIL** [comment]
I’m fine with changing names, but I feel like after the 3 or so hours I put into it we shouldn’t just scrap my system

**Comment by N8python** [comment]
That makes sense. I'll keep the OOP, but perhaps we can make the names less verbose. I'll also close this pull request.

**Pull request closed without merging**
